// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vJzVDh8Rh5E0gxu4zEVIdWenLtGvML8',
    appId: '1:700527118972:web:a74145c9e26fa54021d7f9',
    messagingSenderId: '700527118972',
    projectId: 'aquaspot-postventa',
    authDomain: 'aquaspot-postventa.firebaseapp.com',
    storageBucket: 'aquaspot-postventa.firebasestorage.app',
    measurementId: 'G-D3MX7PRQC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSN5gpuG6TSLVsDJ8s6DoWH-VHCaNTNc',
    appId: '1:700527118972:android:03df495828166e6321d7f9',
    messagingSenderId: '700527118972',
    projectId: 'aquaspot-postventa',
    storageBucket: 'aquaspot-postventa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYHIYRX1hshAspES1lrANKnv2LqE95jYw',
    appId: '1:700527118972:ios:672fc7930e1e476a21d7f9',
    messagingSenderId: '700527118972',
    projectId: 'aquaspot-postventa',
    storageBucket: 'aquaspot-postventa.firebasestorage.app',
    iosBundleId: 'com.aquaspot.aquaspotPostventa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9vJzVDh8Rh5E0gxu4zEVIdWenLtGvML8',
    appId: '1:700527118972:web:60f9cc739e02e63e21d7f9',
    messagingSenderId: '700527118972',
    projectId: 'aquaspot-postventa',
    authDomain: 'aquaspot-postventa.firebaseapp.com',
    storageBucket: 'aquaspot-postventa.firebasestorage.app',
    measurementId: 'G-ZC05ZWWHDG',
  );
}
