// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbyYvscR_mMiTA-oUeGX3aSdpw0PdlDLY',
    appId: '1:699104329538:web:3988b4982e523a923bd2db',
    messagingSenderId: '699104329538',
    projectId: 'aquaspot-postventa-2026',
    authDomain: 'aquaspot-postventa-2026.firebaseapp.com',
    storageBucket: 'aquaspot-postventa-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Bhsx6z7D-52CwD58wjwHgmhN27RrHdk',
    appId: '1:699104329538:android:7d6482446806338b3bd2db',
    messagingSenderId: '699104329538',
    projectId: 'aquaspot-postventa-2026',
    storageBucket: 'aquaspot-postventa-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_lHYD2SCC1YKJNGOIyIkNjELcEm4sJjA',
    appId: '1:699104329538:ios:4ac8ffaea7a895d33bd2db',
    messagingSenderId: '699104329538',
    projectId: 'aquaspot-postventa-2026',
    storageBucket: 'aquaspot-postventa-2026.firebasestorage.app',
    iosBundleId: 'com.aquaspot.aquaspotPostventa',
  );
}
